<a href="https://colab.research.google.com/github/VINAY35T/Batch-51-DM/blob/main/Untitled9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
  "colab": {
  "provenance": []
  },
  "kernelspec": {
  "name": "python3",
  "display_name": "Python 3"
  },
  "language_info": {
  "name": "python"
  }
  },
  "cells": [
  {
  "cell_type": "code",
  "source": [
  "import pandas as pd\n"
  ],
  "metadata": {
  "id": "WPOnHSzOYATv"
  },
  "execution_count": 4,
  "outputs": []
  },
  {
  "cell_type": "code",
  "source": [
  "from sklearn.preprocessing import LabelEncoder, OneHotEncoder"
  ],
  "metadata": {
  "id": "sbPKSu7qYq7R"
  },
  "execution_count": 5,
  "outputs": []
  },
  {
  "cell_type": "code",
  "source": [
  "data = {'Category':['A', 'B', 'C', 'A', 'B']}"
  ],
  "metadata": {
  "id": "3EQhRNYeY5CV"
  },
  "execution_count": 6,
  "outputs": []
  },
  {
  "cell_type": "code",
  "source": [
  "print(data)"
  ],
  "metadata": {
  "colab": {
  "base_uri": "https://localhost:8080/"
  },
  "id": "RFJDDI2oZXO5",
  "outputId": "f34f217e-958a-4681-b71b-daf64dde62a0"
  },
  "execution_count": 7,
  "outputs": [
  {
  "output_type": "stream",
  "name": "stdout",
  "text": [
  "{'Category': ['A', 'B', 'C', 'A', 'B']}\n"
  ]
  }
  ]
  },
  {
  "cell_type": "code",
  "source": [
  "df = pd.DataFrame(data)"
  ],
  "metadata": {
  "id": "cFXpDuEdZci_"
  },
  "execution_count": 8,
  "outputs": []
  },
  {
  "cell_type": "code",
  "source": [
  "print(df)"
  ],
  "metadata": {
  "colab": {
  "base_uri": "https://localhost:8080/"
  },
  "id": "YU5ermzFZlId",
  "outputId": "eb4943e9-cd4a-42b1-8f88-a1507478207a"
  },
  "execution_count": 9,
  "outputs": [
  {
  "output_type": "stream",
  "name": "stdout",
  "text": [
  "  Category\n",
  "0        A\n",
  "1        B\n",
  "2        C\n",
  "3        A\n",
  "4        B\n"
  ]
  }
  ]
  },
  {
  "cell_type": "code",
  "source": [
  "lable_encoder = LabelEncoder()"
  ],
  "metadata": {
  "id": "Sgu3hVoEZq0h"
  },
  "execution_count": 10,
  "outputs": []
  },
  {
  "cell_type": "code",
  "source": [
  "print(lable_encoder)"
  ],
  "metadata": {
  "colab": {
  "base_uri": "https://localhost:8080/"
  },
  "id": "4qXgi2wfcRCq",
  "outputId": "4c4a6b1b-77aa-4509-ae43-cbbf935c9405"
  },
  "execution_count": 21,
  "outputs": [
  {
  "output_type": "stream",
  "name": "stdout",
  "text": [
  "LabelEncoder()\n"
  ]
  }
  ]
  },
  {
  "cell_type": "code",
  "source": [
  "df['lable_Encoded'] = lable_encoder.fit_transform(df['Category'])"
  ],
  "metadata": {
  "id": "XurET3BqZ3Cj"
  },
  "execution_count": 11,
  "outputs": []
  },
  {
  "cell_type": "code",
  "source": [
  "print(df)"
  ],
  "metadata": {
  "colab": {
  "base_uri": "https://localhost:8080/"
  },
  "id": "78j5e_htaLCN",
  "outputId": "d2bebc23-10f1-47cf-9cc6-48b83a78c102"
  },
  "execution_count": 12,
  "outputs": [
  {
  "output_type": "stream",
  "name": "stdout",
  "text": [
  "  Category  lable_Encoded\n",
  "0        A              0\n",
  "1        B              1\n",
  "2        C              2\n",
  "3        A              0\n",
  "4        B              1\n"
  ]
  }
  ]
  },
  {
  "cell_type": "code",
  "source": [
  "one_hot_encoded = pd.get_dummies(df['Category'], prefix='Category')"
  ],
  "metadata": {
  "id": "fILlL-OEaOM0"
  },
  "execution_count": 18,
  "outputs": []
  },
  {
  "cell_type": "code",
  "source": [
  "print(one_hot_encoded)"
  ],
  "metadata": {
  "colab": {
  "base_uri": "https://localhost:8080/"
  },
  "id": "bG07cJWicLQD",
  "outputId": "385650d9-9768-4f11-9fe8-5351b141ae7f"
  },
  "execution_count": 20,
  "outputs": [
  {
  "output_type": "stream",
  "name": "stdout",
  "text": [
  "   Category_A  Category_B  Category_C\n",
  "0        True       False       False\n",
  "1       False        True       False\n",
  "2       False       False        True\n",
  "3        True       False       False\n",
  "4       False        True       False\n"
  ]
  }
  ]
  },
  {
  "cell_type": "code",
  "source": [
  "print(df)"
  ],
  "metadata": {
  "colab": {
  "base_uri": "https://localhost:8080/"
  },
  "id": "sbaGYj4TcHVA",
  "outputId": "799bd710-230d-42fa-d9b3-734df6739dd8"
  },
  "execution_count": 19,
  "outputs": [
  {
  "output_type": "stream",
  "name": "stdout",
  "text": [
  "  Category  lable_Encoded  Category_A  Category_B  Category_C\n",
  "0        A              0        True       False       False\n",
  "1        B              1       False        True       False\n",
  "2        C              2       False       False        True\n",
  "3        A              0        True       False       False\n",
  "4        B              1       False        True       False\n"
  ]
  }
  ]
  },
  {
  "cell_type": "code",
  "source": [
  "df = pd.concat([df, one_hot_encoded], axis=1)"
  ],
  "metadata": {
  "id": "05ydDZ01a9NZ"
  },
  "execution_count": 15,
  "outputs": []
  },
  {
  "cell_type": "code",
  "source": [
  "print(df)"
  ],
  "metadata": {
  "colab": {
  "base_uri": "https://localhost:8080/"
  },
  "id": "hGOeVr2fbAXa",
  "outputId": "ecc7a0d7-f74a-4e8a-ead4-f04a9c0708dc"
  },
  "execution_count": 16,
  "outputs": [
  {
  "output_type": "stream",
  "name": "stdout",
  "text": [
  "  Category  lable_Encoded  Category_A  Category_B  Category_C\n",
  "0        A              0        True       False       False\n",
  "1        B              1       False        True       False\n",
  "2        C              2       False       False        True\n",
  "3        A              0        True       False       False\n",
  "4        B              1       False        True       False\n"
  ]
  }
  ]
  },
  {
  "cell_type": "code",
  "source": [],
  "metadata": {
  "id": "QAv6I4NVcYZM"
  },
  "execution_count": null,
  "outputs": []
  },
  {
  "cell_type": "code",
  "source": [
  "from datetime import datetime"
  ],
  "metadata": {
  "id": "Wx6r7Hq7c3B2"
  },
  "execution_count": 22,
  "outputs": []
  },
  {
  "cell_type": "code",
  "source": [
  "data = {'Name':['Virat', 'Hardik'], 'Date_of_Birth': ['2004-08-19', '2006-05-08']}"
  ],
  "metadata": {
  "id": "x75JjUModR1x"
  },
  "execution_count": 23,
  "outputs": []
  },
  {
  "cell_type": "code",
  "source": [
  "print (data)"
  ],
  "metadata": {
  "colab": {
  "base_uri": "https://localhost:8080/"
  },
  "id": "EvpmRf4teODy",
  "outputId": "7150ae65-e2ab-4adc-a066-fc875354b586"
  },
  "execution_count": 24,
  "outputs": [
  {
  "output_type": "stream",
  "name": "stdout",
  "text": [
  "{'Name': ['Virat', 'Hardik'], 'Date_of_Birth': ['2004-08-19', '2006-05-08']}\n"
  ]
  }
  ]
  },
  {
  "cell_type": "code",
  "source": [
  "df = pd.DataFrame(data)"
  ],
  "metadata": {
  "id": "hi3isziceVDk"
  },
  "execution_count": 25,
  "outputs": []
  },
  {
  "cell_type": "code",
  "source": [
  "print (df)"
  ],
  "metadata": {
  "colab": {
  "base_uri": "https://localhost:8080/"
  },
  "id": "mTAXn0TOeZzL",
  "outputId": "28dcc09b-913b-4aca-a574-fd1b01807d02"
  },
  "execution_count": 26,
  "outputs": [
  {
  "output_type": "stream",
  "name": "stdout",
  "text": [
  "     Name Date_of_Birth\n",
  "0   Virat    2004-08-19\n",
  "1  Hardik    2006-05-08\n"
  ]
  }
  ]
  },
  {
  "cell_type": "code",
  "source": [
  "df['Date_of_Birth'] = pd.to_datetime(df['Date_of_Birth'])"
  ],
  "metadata": {
  "id": "J4eTlyxHej2q"
  },
  "execution_count": 27,
  "outputs": []
  },
  {
  "cell_type": "code",
  "source": [
  "print (df)"
  ],
  "metadata": {
  "colab": {
  "base_uri": "https://localhost:8080/"
  },
  "id": "9GvPalX6fowv",
  "outputId": "1f05c888-426c-40d0-ec26-ebd4e3f13d92"
  },
  "execution_count": 28,
  "outputs": [
  {
  "output_type": "stream",
  "name": "stdout",
  "text": [
  "     Name Date_of_Birth\n",
  "0   Virat    2004-08-19\n",
  "1  Hardik    2006-05-08\n"
  ]
  }
  ]
  },
  {
  "cell_type": "code",
  "source": [],
  "metadata": {
  "id": "FfVhI9V3ftY4"
  },
  "execution_count": null,
  "outputs": []
  }
  ]
  }

NameError: name 'null' is not defined